### PR TITLE
switch nav and content

### LINKED ISSUE #215: [Design] Page titles
Currently the page title is aligned to the left with the sidebar. It sometime feels weird as if the title is not directly related to the content.

Maybe we could review an option to move the page title directly in the content flow.

(might be fixed if we change layout in #214)

### PR DESCRIPTION
**Pull request by eddiemonge**
switch the context nav and content. content is now on the left and the subnav is on the right.

fixes #215

### CODE REVIEW

**Comment by SBoudrias** [comment]
Can we see a screenshot?

**Comment by eddiemonge** [comment]
mobile dont show it anyway:
mobiledontshow

no difference for non-nav pages:
nodiff

example 1:
right

example 2:
right2

example 3 scrolled:
right3

**Comment by SBoudrias** [comment]
Could we align the title and the text on the right side? Right now they seem to be displaced by I'd say ~10px

**Comment by eddiemonge** [comment]
you mean left right? I left aligned the title and content

**Comment by SBoudrias** [comment]
Awesome!!

**Pull request merged**
