### PR TITLE
Fix minor grammar issues in migration page

### PR DESCRIPTION
**Pull request by polybuildr**

### CODE REVIEW

**Comment by hemanth** [comment]
Thanks.

**Comment by arthurvr** [comment]
That's better indeed. Thanks.

**Comment by arthurvr** [comment]
@hemanth was just a second faster :p

**Comment by hemanth** [comment]
@arthurvr heh heh :P

**Comment by polybuildr** [comment]
Wow, two responses within a minute? You guys are fast! :P

**Pull request merged**
