### PR TITLE
Update install command

### PR DESCRIPTION
**Pull request by mehrdadrafiee**
`-g` or `--global` are deprecated. using `--location=global` flag instead.

### CODE REVIEW

**Comment by mischah** [comment]
### <span aria-hidden="true">👷</span> Deploy Preview for *yeoman* processing.


|  Name | Link |
|:-:|------------------------|
|<span aria-hidden="true">🔨</span> Latest commit | 2e1a2b0faacdf9262e105bdd6a0b19ebe428e95a |
|<span aria-hidden="true">🔍</span> Latest deploy log | https://app.netlify.com/sites/yeoman/deploys/64647c9cc447240008ee796b |

**Review by mischah — COMMENTED** [review]
I’m confused 🤔 

I don’t find anything in the docs.

Neither [here](https://docs.npmjs.com/downloading-and-installing-packages-globally), nor [there](https://docs.npmjs.com/cli/v9/commands/npm-install#global).

**Comment by eddiemonge** [comment]
This was a windows issue that has since been reverted: https://github.com/npm/cli/issues/4980#issuecomment-1145164050

**Comment by mischah** [comment]
Thanks for the clarification Eddie :octocat:

**Pull request closed without merging**
