### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by rainabba**
Added details about removing a linked version for testing cycles.

### CODE REVIEW

**Comment by SBoudrias** [comment]
You don't need to remove anything prior to linking or installing.

Are you sure you were using the latest NPM and that this was an issue for you?

**Comment by rainabba** [comment]
I didn't need to prior to linking. I did need to after making changes because otherwise I was seeing the last build and I couldn't link again without uninstalling. I will make sure that I'm on the latest NPM and try again then reply back here to confirm either way.

**Comment by SBoudrias** [comment]
Your issue can also be related to global/local install folders.

**Comment by rainabba** [comment]
Running Node v0.12.6 and NPM 2.11.2.

1. Made a change to a generator (working on generator-hapi-composer to make it Hapi 8 compatible)
2. Cleared my project folder and ran `yo hapi-composer` the same way I have been
3. Resulting project did not reflect my latest changes
4. In the generator project, I ran `npm uninstall genertor-hapi-composer -g` then `npm link`
5. repeat steps 1-3, but this time the changes were in place

That is consistent with what I've been seeing all day. What sort of global/local install folder might I be having (that affects nothing else)? Do I need to mention that I'm on Windows (even though that isn't supposed to matter with Node.js)?

**Pull request closed without merging**
