### PR TITLE
cmder link was dead

### PR DESCRIPTION
**Pull request by BenjaminTodts**

### CODE REVIEW

**Comment by arthurvr** [comment]
Should probably link to http://cmder.net/ instead. WDYT?

**Comment by arthurvr** [comment]
Thanks for the PR, by the way :)

**Comment by BenjaminTodts** [comment]
Even better!

**Comment by addyosmani** [comment]
Link to Cmder.net sgtm!

**Comment by eddiemonge** [comment]
Changed it for you. Thanks for pointing it out @BenjaminTodts

**Pull request closed without merging**
