### PR TITLE
[BUGFIX] change withPrompt to withPrompts

### PR DESCRIPTION
**Pull request by markusfalk**
There was a missing 's'

### CODE REVIEW

**Comment by kevva** [comment]
It should be `withPrompt`.

**Comment by markusfalk** [comment]
are you sure? http://yeoman.github.io/generator/RunContext.html

**Comment by kevva** [comment]
`Deprecated:`

**Comment by markusfalk** [comment]
It took me 3 days to find out why my rund wouldn't work ;) I was pretty sure

**Comment by SBoudrias** [comment]
Oh nice catch! Thanks a lot!

**Pull request merged**
