### PR TITLE
Unable to create new todos - $scope.todo is undefined

### PR DESCRIPTION
**Pull request by opreaadrian**
While working through the tutorial, I found that creating a new "todo" item was not possible given the way `$scope` is treated when using `ng-include`. I modified all references to `$scope.todo` to `this.todo` in order for the application to work.

https://github.com/angular/angular.js/wiki/Understanding-Scopes
http://stackoverflow.com/questions/11412410/angularjs-losing-scope-when-using-ng-include

### CODE REVIEW

**Comment by eddiemonge** [comment]
Is this still valid or can it be closed?

**Comment by opreaadrian** [comment]
I'm not sure as I've managed to get the example working by applying the changes I've submitted with this patch. If it would help, I can try again following the example on the website and let you know. Maybe there was a change in Angular that fixed that. Let me know if you'd like me to go through the example again.

**Comment by eddiemonge** [comment]
If you can go through it again please that would be helpful. Both to test this bug and another reviewer never hurts

**Comment by pmareke** [comment]
As I said in another issue:

Hi, first of all thanks for the generator! It's so awesome and for the beginners like me is quite helpful!

In refer to the error I had a problem with the $scope in the Step 6 because when I added item to the "todos" the $scope.todo was undefined.

So I had to change the position of the ng-controller="MainCrtl" to inside of the main.html instead of index.html container.

Thanks again!

**Comment by SBoudrias** [comment]
@eddiemonge Can you follow up with the correct resolution. Either merging, adding another fix or closing this PR?

**Comment by eddiemonge** [comment]
I feel like this should be closed but I'd have to go through it to see. Im double inclined to close since there haven't really been any other issues complaining about it.

**Comment by eddiemonge** [comment]
Yeah double checked and followed the instructions and its fine

**Pull request closed without merging**
