### PR TITLE
Added links to Arabic articles

### PR DESCRIPTION
**Pull request by 7oot**

### CODE REVIEW

**Comment by eddiemonge** [comment]
is Arabic the correct word here?

**Comment by 7oot** [comment]
yeah!... but why? not sure I get what you mean!

**Comment by 7oot** [comment]
so... um... now what?!

**Comment by SBoudrias** [comment]
We already have link in Russian in there, but I wonder if we should. Does it make sense to link to articles we can't review and vet?

**Comment by arthurvr** [comment]
> We already have link in Russian in there, but I wonder if we should. Does it make sense to link to articles we can't review and vet?

Yeah, I would rather see us removing the russian ones as well. We can't review the articles and those articles only make sense to a really small amount of readers.

**Comment by eddiemonge** [comment]
I think this and those should go in the monthly newsletter

**Comment by arthurvr** [comment]
> I think this and those should go in the monthly newsletter

Still, then I'd first like to be able to review those articles first.

**Comment by arthurvr** [comment]
Consensus on this one? Do we remove the Russian articles and don't merge this one in, or just collect them for the time being and think about a better solution later on?

**Comment by SBoudrias** [comment]
Let's follow up with removing the Russian articles.

**Pull request closed without merging**
